{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Analytical-M03.IconDef-WorkerPortrait-Analytical-M03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAnalytical',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDurabilityHigh' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t02',
  attributes:
   { gender: '1',
     level: 11,
     squad_slot_idx: 1,
     item_seen: true,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Curious-M03.IconDef-WorkerPortrait-Curious-M03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: 'squad_attribute_arms_fireteamalpha',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsShieldRegenLow' },
  quantity: 1 }
{ templateId: 'Worker:managertrainer_uc_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-PersonalTrainer-F01.IconDef-ManagerPortrait-PersonalTrainer-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: 'squad_attribute_medicine_trainingteam',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsTrainer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-M03.IconDef-WorkerPortrait-Competitive-M03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Adventurous-F02.IconDef-WorkerPortrait-Adventurous-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: 'squad_attribute_arms_closeassaultsquad',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsRangedDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-M03.IconDef-WorkerPortrait-Competitive-M03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:managergadgeteer_uc_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Gadgeteer-F01.IconDef-ManagerPortrait-Gadgeteer-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCooperative',
     squad_id: 'squad_attribute_scavenging_gadgeteers',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsGadgeteer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 3,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Adventurous-M02.IconDef-WorkerPortrait-Adventurous-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: 'squad_attribute_medicine_emtsquad',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsMeleeDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-F03.IconDef-WorkerPortrait-Competitive-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsShieldRegenLow' },
  quantity: 1 }
{ templateId: 'Worker:managerengineer_c_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Engineer-M01.IconDef-ManagerPortrait-Engineer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsEngineer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_sr_t02',
  attributes:
   { gender: '2',
     level: 20,
     squad_slot_idx: 1,
     item_seen: true,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Cooperative-F01.IconDef-WorkerPortrait-Cooperative-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCooperative',
     squad_id: 'squad_attribute_scavenging_gadgeteers',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dependable-M01.IconDef-WorkerPortrait-Dependable-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDependable',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsShieldRegenLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 10,
     item_seen: true,
     squad_slot_idx: 2,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Curious-F01.IconDef-WorkerPortrait-Curious-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: 'squad_attribute_arms_fireteamalpha',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsShieldRegenLow' },
  quantity: 1 }
{ templateId: 'Worker:managergadgeteer_c_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Gadgeteer-M01.IconDef-ManagerPortrait-Gadgeteer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsGadgeteer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-F02.IconDef-WorkerPortrait-Pragmatic-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsMeleeDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Cooperative-M02.IconDef-WorkerPortrait-Cooperative-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCooperative',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsFortitudeLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Analytical-M03.IconDef-WorkerPortrait-Analytical-M03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAnalytical',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsFortitudeLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '1',
     level: 1,
     squad_slot_idx: 2,
     item_seen: true,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-M01.IconDef-WorkerPortrait-Pragmatic-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: 'squad_attribute_scavenging_scoutingparty',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDurabilityHigh' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_c_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Curious-M01.IconDef-WorkerPortrait-Curious-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsMeleeDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 2,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Adventurous-F01.IconDef-WorkerPortrait-Adventurous-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 2,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dreamer-F02.IconDef-WorkerPortrait-Dreamer-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: 'squad_attribute_synthesis_thethinktank',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDurabilityHigh' },
  quantity: 1 }
{ templateId: 'Worker:managermartialartist_c_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-MartialArtist-F01.IconDef-ManagerPortrait-MartialArtist-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: 'squad_attribute_arms_closeassaultsquad',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsMartialArtist',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-F01.IconDef-WorkerPortrait-Pragmatic-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:managerdoctor_r_t01',
  attributes:
   { gender: '1',
     level: 5,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Doctor-M01.IconDef-ManagerPortrait-Doctor-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: 'squad_attribute_medicine_emtsquad',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsDoctor',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 3,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Cooperative-F03.IconDef-WorkerPortrait-Cooperative-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCooperative',
     squad_id: 'squad_attribute_scavenging_gadgeteers',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsMeleeDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-M03.IconDef-WorkerPortrait-Pragmatic-M03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsRangedDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 3,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dreamer-M03.IconDef-WorkerPortrait-Dreamer-M03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: 'squad_attribute_synthesis_thethinktank',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsRangedDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_c_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-M01.IconDef-WorkerPortrait-Competitive-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsFortitudeLow' },
  quantity: 1 }
{ templateId: 'Worker:managerinventor_c_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Inventor-F01.IconDef-ManagerPortrait-Inventor-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsInventor',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dependable-M01.IconDef-WorkerPortrait-Dependable-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDependable',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsResistanceLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dreamer-F03.IconDef-WorkerPortrait-Dreamer-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: 'squad_attribute_medicine_trainingteam',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsShieldRegenLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_sr_t01',
  attributes:
   { gender: '1',
     level: 10,
     item_seen: true,
     squad_slot_idx: 3,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-M01.IconDef-WorkerPortrait-Pragmatic-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: 'squad_attribute_scavenging_scoutingparty',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsResistanceLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 2,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Cooperative-F02.IconDef-WorkerPortrait-Cooperative-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCooperative',
     squad_id: 'squad_attribute_scavenging_gadgeteers',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsResistanceLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-M02.IconDef-WorkerPortrait-Pragmatic-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsShieldRegenLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_sr_t02',
  attributes:
   { gender: '2',
     level: 20,
     squad_slot_idx: 1,
     item_seen: true,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-F03.IconDef-WorkerPortrait-Pragmatic-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: 'squad_attribute_scavenging_scoutingparty',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dependable-F01.IconDef-WorkerPortrait-Dependable-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDependable',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDurabilityHigh' },
  quantity: 1 }
{ templateId: 'Worker:managerdoctor_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Doctor-F01.IconDef-ManagerPortrait-Doctor-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsDoctor',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 3,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Curious-F03.IconDef-WorkerPortrait-Curious-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: 'squad_attribute_synthesis_corpsofengineering',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 2,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dreamer-M01.IconDef-WorkerPortrait-Dreamer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: 'squad_attribute_medicine_trainingteam',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsFortitudeLow' },
  quantity: 1 }
{ templateId: 'Worker:managergadgeteer_uc_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Gadgeteer-M01.IconDef-ManagerPortrait-Gadgeteer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCooperative',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsGadgeteer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_uc_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-F02.IconDef-WorkerPortrait-Competitive-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Analytical-F02.IconDef-WorkerPortrait-Analytical-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAnalytical',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Analytical-M02.IconDef-WorkerPortrait-Analytical-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAnalytical',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsMeleeDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 2,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Adventurous-M02.IconDef-WorkerPortrait-Adventurous-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: 'squad_attribute_medicine_emtsquad',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsFortitudeLow' },
  quantity: 1 }
{ templateId: 'Worker:managerengineer_vr_t01',
  attributes:
   { gender: '2',
     level: 2,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Engineer-F01.IconDef-ManagerPortrait-Engineer-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: 'squad_attribute_synthesis_corpsofengineering',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsEngineer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Cooperative-F01.IconDef-WorkerPortrait-Cooperative-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCooperative',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsFortitudeLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-F02.IconDef-WorkerPortrait-Pragmatic-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDurabilityHigh' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 2,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Adventurous-F03.IconDef-WorkerPortrait-Adventurous-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: 'squad_attribute_arms_closeassaultsquad',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsResistanceLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-M01.IconDef-WorkerPortrait-Competitive-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsFortitudeLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 2,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Curious-F01.IconDef-WorkerPortrait-Curious-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: 'squad_attribute_synthesis_corpsofengineering',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_c_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dreamer-M03.IconDef-WorkerPortrait-Dreamer-M03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-F02.IconDef-WorkerPortrait-Competitive-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDurabilityHigh' },
  quantity: 1 }
{ templateId: 'Worker:managerexplorer_r_t01',
  attributes:
   { gender: '2',
     level: 5,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Explorer-F01.IconDef-ManagerPortrait-Explorer-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: 'squad_attribute_scavenging_scoutingparty',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsExplorer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dreamer-M02.IconDef-WorkerPortrait-Dreamer-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsResistanceLow' },
  quantity: 1 }
{ templateId: 'Worker:managerinventor_uc_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Inventor-M01.IconDef-ManagerPortrait-Inventor-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: 'squad_attribute_synthesis_thethinktank',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsInventor',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Pragmatic-M02.IconDef-WorkerPortrait-Pragmatic-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDurabilityHigh' },
  quantity: 1 }
{ templateId: 'Worker:managerexplorer_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Explorer-M01.IconDef-ManagerPortrait-Explorer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsExplorer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Analytical-F03.IconDef-WorkerPortrait-Analytical-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAnalytical',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsShieldRegenLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-M01.IconDef-WorkerPortrait-Competitive-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsShieldRegenLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dreamer-M01.IconDef-WorkerPortrait-Dreamer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: 'squad_attribute_synthesis_thethinktank',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsMeleeDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 7,
     item_seen: true,
     squad_slot_idx: 3,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Curious-F03.IconDef-WorkerPortrait-Curious-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: 'squad_attribute_arms_fireteamalpha',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsFortitudeLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 3,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Dreamer-M01.IconDef-WorkerPortrait-Dreamer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsDreamer',
     squad_id: 'squad_attribute_medicine_trainingteam',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsRangedDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:managersoldier_r_t02',
  attributes:
   { gender: '2',
     level: 20,
     squad_slot_idx: 0,
     item_seen: true,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Marksman-F01.IconDef-ManagerPortrait-Marksman-F01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: 'squad_attribute_arms_fireteamalpha',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsSoldier',
     favorite: true,
     building_slot_used: -1 },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Competitive-F03.IconDef-WorkerPortrait-Competitive-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCompetitive',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '1',
     level: 5,
     item_seen: true,
     squad_slot_idx: 1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Adventurous-M02.IconDef-WorkerPortrait-Adventurous-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: 'squad_attribute_medicine_emtsquad',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:managergadgeteer_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Gadgeteer-M01.IconDef-ManagerPortrait-Gadgeteer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsPragmatic',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsGadgeteer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_c_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: -1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Curious-F02.IconDef-WorkerPortrait-Curious-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:managerengineer_c_t02',
  attributes:
   { gender: '1',
     level: 10,
     squad_slot_idx: 0,
     item_seen: true,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-ManagerPortrait-Engineer-M01.IconDef-ManagerPortrait-Engineer-M01',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAnalytical',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     managerSynergy: 'Homebase.Manager.IsEngineer',
     building_slot_used: -1,
     favorite: false },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '1',
     level: 1,
     item_seen: true,
     squad_slot_idx: 3,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Adventurous-M02.IconDef-WorkerPortrait-Adventurous-M02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsAdventurous',
     squad_id: 'squad_attribute_arms_closeassaultsquad',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsTrapDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_r_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 0,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Cooperative-F03.IconDef-WorkerPortrait-Cooperative-F03',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCooperative',
     squad_id: '',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsAbilityDamageLow' },
  quantity: 1 }
{ templateId: 'Worker:workerbasic_vr_t01',
  attributes:
   { gender: '2',
     level: 1,
     item_seen: true,
     squad_slot_idx: 1,
     portrait: '/Game/UI/Icons/Icon-Worker/IconDefinitions/IconDef-WorkerPortrait-Curious-F02.IconDef-WorkerPortrait-Curious-F02',
     max_level_bonus: 0,
     personality: 'Homebase.Worker.Personality.IsCurious',
     squad_id: 'squad_attribute_synthesis_corpsofengineering',
     xp: 0,
     slotted_building_id: '',
     building_slot_used: -1,
     favorite: false,
     set_bonus: 'Homebase.Worker.SetBonus.IsRangedDamageLow' },
  quantity: 1 }
